apiVersion: v1
kind: Service
metadata:
  name: rails-budget-app-service
  labels:
    app: rails-budget-app-service
spec:
  type: ClusterIP
  selector:
    app: rails-budget-app
  ports:
    - port: 80
      targetPort: 3000
