apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-gitops-app
  namespace: argocd  # ArgoCD's namespace inside k8s cluster
spec:
  project: default
  source:
    repoURL: https://github.com/SST-Bappu/rail_app_k8s_gitops.git
    targetRevision: master
    path: k8s-manifests  # Directory inside the repo where YAMLs are
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Or the namespace where the app should be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
